name: Tests

on:
  push:
    branches: ["*"]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ™ Git Checkout
        uses: actions/checkout@v3

      - name: ğŸ Prepare Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: ğŸ Install Poetry
        run: pip install poetry

      - name: ğŸ Install dependencies
        run: poetry install --no-interaction

      - name: ğŸ§ª Run tests
        run: poetry run pytest --github-report -vvv
